baseURL: http://example.org/
languageCode: en-us
theme: "PaperMod"
theme: PaperMod
title: Ho Ho Ho! 
description: "Tracking Christmas through Music"

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  assets: 
      favicon: "img/favicon.ico"

homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

menu:
  main:
    - identifier: code
      name: code
      url: /code/
      weight: 40
    - identifier: songs
      name: songs
      url: /songs/
      weight: 10
    - identifier: stations
      name: stations
      url: /stations/
      weight: 20
    - identifier: artists
      name: artists
      url: /artists/
      weight: 30

profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
